version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Mongey/terraform-provider-kafka
    docker:
      - image: circleci/golang:1.10
        environment:
          TEST_RESULTS: /tmp/test-results
      - image: confluentinc/cp-zookeeper:latest
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
      - image: confluentinc/cp-kafka:4.0.0-2
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    steps:
      - checkout
      - run: go build
      - store_artifacts:
          path: /go/src/github.com/Mongey/terraform-provider-kafka/terraform-provider-kafka
          destination: terraform-provider-kafka
      - run: make test
      - run: go get github.com/jstemmer/go-junit-report
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run Tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make testacc| tee ${TEST_RESULTS}/go-test.out
      - store_test_results:
          path: /tmp/test-results
